<?php

return [
    /*
    |--------------------------------------------------------------------------
    | State Repository
    |--------------------------------------------------------------------------
    |
    | The repository used to persist workflow state.
    |
    | Supported: "null", "session", "eloquent"
    |
    | - null: No persistence (stateless)
    | - session: Store in Laravel session (deprecated)
    | - eloquent: Store in database (recommended; requires migration)
    |
    */
    'repository' => env('WORKFLOWS_REPOSITORY', 'eloquent'),

    /*
    |--------------------------------------------------------------------------
    | Middleware
    |--------------------------------------------------------------------------
    |
    | Middleware applied to all workflow routes.
    | You can add 'auth' here to protect all workflows.
    |
    */
    'middleware' => ['web'],

    /*
    |--------------------------------------------------------------------------
    | Resume Links
    |--------------------------------------------------------------------------
    |
    | Configuration for signed resume URLs generated by resumeUrlFor().
    | Resume links require the Eloquent state repository.
    |
    */
    'resume' => [
        'default_expires_minutes' => env('WORKFLOWS_RESUME_EXPIRES', 1440),
    ],
];
